services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=k_small_banking_rest'
      - 'POSTGRES_PASSWORD=small_bank'
      - 'POSTGRES_USER=small_bank'
    ports:
      - '5432:5432'
    volumes:
      - small_bank_postgres_data:/var/lib/postgresql/data






volumes:
  small_bank_postgres_data:
    name: small_banking_postgres_data