spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/k_small_banking_rest}
    username: ${SPRING_DATASOURCE_USERNAME:small_bank}
    password: ${SPRING_DATASOURCE_PASSWORD:small_bank}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariCP
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: WARN
        type.descriptor.sql.BasicBinder: WARN
      springframework:
        security: WARN
        web: INFO
    gg.jte: WARN
    com:
      ilkinmehdiyev: INFO