server:
  port: 8080
  ssl:
    bundle: "server"
    enabled-protocols: TLSv1.3
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/k_small_banking_rest}
    username: ${SPRING_DATASOURCE_USERNAME:small_bank}
    password: ${SPRING_DATASOURCE_PASSWORD:small_bank}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariCP
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "server"
          keystore:
            location: ${SSL_KEYSTORE_LOCATION:classpath:keystore.p12}
            password: "QTntL1pa4QrJcf5R"
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:cert.pem"
  threads:
    virtual:
      enabled: true
  application:
    name: k_small_banking
  main:
    banner-mode: off
  profiles:
    include:
      - security

logging:
  level:
    root: INFO
    org:
      springframework:
        security: WARN
        web: INFO
    com:
      ilkinmehdiyev: INFO

#security:
#  jwt-properties:
#    secret-key: "Y2FzY2FkZS1haS1pcGwtdDIwLXdvcmxkLWN1cC0yMDI0LWRldmVsb3Blci1rbm93bGVkZ2UtYmFzZQ=="
#    token-validity-in-seconds: 86400
#    token-validity-in-seconds-for-remember-me: 2592000
#    refresh-token:
#      expiration: 604800